# ⚠️ disabled for release version 1.0
#
# version: 2
# updates:
#   - package-ecosystem: composer
#     directory: "/"
#     schedule:
#       interval: daily
#       time: "23:00"
#     open-pull-requests-limit: 10
#     reviewers:
#       - ezralazuardy
#   - package-ecosystem: npm
#     directory: "/"
#     schedule:
#       interval: daily
#       time: "23:00"
#     open-pull-requests-limit: 10
#     reviewers:
#       - ezralazuardy
